name: Installer
on: workflow_dispatch
jobs:
  job:
    defaults:
      run:
        working-directory: ./installer
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Build
      run: python build.py
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: installer/dist/
  merge:
    name: Merge artifacts
    runs-on: ubuntu-latest
    needs: job
    steps:
    - uses: actions/upload-artifact/merge@v4
      with:
        name: artifacts
        delete-merged: true
    